In [2]:
import numpy as np
import pandas as pd

In [3]:
df1SE=pd.DataFrame({'StudentID':[9,11,13,15,17,19,21,23,25,27,29], 'ScoreSE':[34,65,45,88,77,65,67,81,21,26,39]})
df2SE=pd.DataFrame({'StudentID':[2,4,6,8,10,12,14,16,18,20,22,24,26,28,30], 'ScoreSE':[34,76,56,46,9,70,83,26,55,72,16,33,38,50,44]})
df1ML=pd.DataFrame({'StudentID':[1,3,5,7,9,11,13,15,17,19,21,23,25,27,29], 'ScoreML':[30,89,95,76,34,52,15,12,79,99,44,42,27,51,16]})
df2ML=pd.DataFrame({'StudentID':[2,4,6,8,10,12,14,16,18,20], 'ScoreML':[32,5,42,87,67,53,63,22,19,75]})

In [4]:
dfSE=pd.concat([df1SE,df2SE],ignore_index=True)
dfML=pd.concat([df1ML,df2ML],ignore_index=True)
df=pd.concat([dfSE,dfML],axis=1)
df

    StudentID  ScoreSE  StudentID  ScoreML
0           9       34        1.0     30.0
1          11       65        3.0     89.0
2          13       45        5.0     95.0
3          15       88        7.0     76.0
4          17       77        9.0     34.0
5          19       65       11.0     52.0
6          21       67       13.0     15.0
7          23       81       15.0     12.0
8          25       21       17.0     79.0
9          27       26       19.0     99.0
10         29       39       21.0     44.0
11          2       34       23.0     42.0
12          4       76       25.0     27.0
13          6       56       27.0     51.0
14          8       46       29.0     16.0
15         10        9        2.0     32.0
16         12       70        4.0      5.0
17         14       83        6.0     42.0
18         16       26        8.0     87.0
19         18       55       10.0     67.0
20         20       72       12.0     53.0
21         22       16       14.0     63.0
22         24       33       16.0     22.0
23         26       38       18.0     19.0
24         28       50       20.0     75.0
25         30       44        NaN      NaN

In [5]:
dfSE=pd.concat([df1SE,df2SE],ignore_index=True)
dfML=pd.concat([df1ML,df2ML],ignore_index=True)
df=dfSE.merge(dfML,how='inner')
df

    StudentID  ScoreSE  ScoreML
0           9       34       34
1          11       65       52
2          13       45       15
3          15       88       12
4          17       77       79
5          19       65       99
6          21       67       44
7          23       81       42
8          25       21       27
9          27       26       51
10         29       39       16
11          2       34       32
12          4       76        5
13          6       56       42
14          8       46       87
15         10        9       67
16         12       70       53
17         14       83       63
18         16       26       22
19         18       55       19
20         20       72       75

In [6]:
dfSE=pd.concat([df1SE,df2SE],ignore_index=True)
dfML=pd.concat([df1ML,df2ML],ignore_index=True)
df=dfSE.merge(dfML,how='left')
df

    StudentID  ScoreSE  ScoreML
0           9       34     34.0
1          11       65     52.0
2          13       45     15.0
3          15       88     12.0
4          17       77     79.0
5          19       65     99.0
6          21       67     44.0
7          23       81     42.0
8          25       21     27.0
9          27       26     51.0
10         29       39     16.0
11          2       34     32.0
12          4       76      5.0
13          6       56     42.0
14          8       46     87.0
15         10        9     67.0
16         12       70     53.0
17         14       83     63.0
18         16       26     22.0
19         18       55     19.0
20         20       72     75.0
21         22       16      NaN
22         24       33      NaN
23         26       38      NaN
24         28       50      NaN
25         30       44      NaN

In [7]:
dfSE=pd.concat([df1SE,df2SE],ignore_index=True)
dfML=pd.concat([df1ML,df2ML],ignore_index=True)
df=dfSE.merge(dfML,how='right')
df

    StudentID  ScoreSE  ScoreML
0           1      NaN       30
1           3      NaN       89
2           5      NaN       95
3           7      NaN       76
4           9     34.0       34
5          11     65.0       52
6          13     45.0       15
7          15     88.0       12
8          17     77.0       79
9          19     65.0       99
10         21     67.0       44
11         23     81.0       42
12         25     21.0       27
13         27     26.0       51
14         29     39.0       16
15          2     34.0       32
16          4     76.0        5
17          6     56.0       42
18          8     46.0       87
19         10      9.0       67
20         12     70.0       53
21         14     83.0       63
22         16     26.0       22
23         18     55.0       19
24         20     72.0       75

In [8]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [9]:
stacked = dframe1.stack()
stacked

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [10]:
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [11]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])
frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN

In [12]:
df.describe()

       StudentID    ScoreSE    ScoreML
count  25.000000  21.000000  25.000000
mean   13.400000  54.047619  49.040000
std     8.025999  23.007556  28.265822
min     1.000000   9.000000   5.000000
25%     7.000000  34.000000  27.000000
50%    13.000000  56.000000  44.000000
75%    19.000000  72.000000  75.000000
max    29.000000  88.000000  99.000000