In [1]:
import numpy as np
import pandas as pd
data=np.arange(30,58).reshape(7,4)
dfx=pd.DataFrame(data, index=['apple','banana','kiwi','grape','mango','orange','pineapple'],columns=['Store1','Store2','Store3','Store4'])
dfx

           Store1  Store2  Store3  Store4
apple          30      31      32      33
banana         34      35      36      37
kiwi           38      39      40      41
grape          42      43      44      45
mango          46      47      48      49
orange         50      51      52      53
pineapple      54      55      56      57

In [2]:
dfx['Store5']=np.nan
dfx.loc['watermelon']=np.arange(30,35)
dfx.loc['strawberry']=np.nan
dfx['Store6']=np.nan
dfx['Store4']['apple']=35
dfx

/tmp/ipykernel_743/2751060872.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['Store4']['apple']=35

            Store1  Store2  Store3  Store4  Store5  Store6
apple         30.0    31.0    32.0    35.0     NaN     NaN
banana        34.0    35.0    36.0    37.0     NaN     NaN
kiwi          38.0    39.0    40.0    41.0     NaN     NaN
grape         42.0    43.0    44.0    45.0     NaN     NaN
mango         46.0    47.0    48.0    49.0     NaN     NaN
orange        50.0    51.0    52.0    53.0     NaN     NaN
pineapple     54.0    55.0    56.0    57.0     NaN     NaN
watermelon    30.0    31.0    32.0    33.0    34.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN     NaN

In [3]:
dfx.isnull()

            Store1  Store2  Store3  Store4  Store5  Store6
apple        False   False   False   False    True    True
banana       False   False   False   False    True    True
kiwi         False   False   False   False    True    True
grape        False   False   False   False    True    True
mango        False   False   False   False    True    True
orange       False   False   False   False    True    True
pineapple    False   False   False   False    True    True
watermelon   False   False   False   False   False    True
strawberry    True    True    True    True    True    True

In [4]:
dfx.notnull()

            Store1  Store2  Store3  Store4  Store5  Store6
apple         True    True    True    True   False   False
banana        True    True    True    True   False   False
kiwi          True    True    True    True   False   False
grape         True    True    True    True   False   False
mango         True    True    True    True   False   False
orange        True    True    True    True   False   False
pineapple     True    True    True    True   False   False
watermelon    True    True    True    True    True   False
strawberry   False   False   False   False   False   False

In [5]:
dfx.isnull().sum()

Store1    1
Store2    1
Store3    1
Store4    1
Store5    8
Store6    9
dtype: int64

In [6]:
dfx.isnull().sum().sum()

np.int64(21)

In [7]:
dfx.count()

Store1    8
Store2    8
Store3    8
Store4    8
Store5    1
Store6    0
dtype: int64

In [8]:
dfx.Store5[dfx.Store5.notnull()]

watermelon    34.0
Name: Store5, dtype: float64

In [9]:
dfx.Store5.dropna()

watermelon    34.0
Name: Store5, dtype: float64

In [10]:
dfx.dropna()

Empty DataFrame
Columns: [Store1, Store2, Store3, Store4, Store5, Store6]
Index: []

In [11]:
dfx.dropna(how='all')

            Store1  Store2  Store3  Store4  Store5  Store6
apple         30.0    31.0    32.0    35.0     NaN     NaN
banana        34.0    35.0    36.0    37.0     NaN     NaN
kiwi          38.0    39.0    40.0    41.0     NaN     NaN
grape         42.0    43.0    44.0    45.0     NaN     NaN
mango         46.0    47.0    48.0    49.0     NaN     NaN
orange        50.0    51.0    52.0    53.0     NaN     NaN
pineapple     54.0    55.0    56.0    57.0     NaN     NaN
watermelon    30.0    31.0    32.0    33.0    34.0     NaN

In [12]:
dfx.dropna(how='all',axis=1)

            Store1  Store2  Store3  Store4  Store5
apple         30.0    31.0    32.0    35.0     NaN
banana        34.0    35.0    36.0    37.0     NaN
kiwi          38.0    39.0    40.0    41.0     NaN
grape         42.0    43.0    44.0    45.0     NaN
mango         46.0    47.0    48.0    49.0     NaN
orange        50.0    51.0    52.0    53.0     NaN
pineapple     54.0    55.0    56.0    57.0     NaN
watermelon    30.0    31.0    32.0    33.0    34.0
strawberry     NaN     NaN     NaN     NaN     NaN

In [13]:
dfx.dropna(thresh=5,axis=1)

            Store1  Store2  Store3  Store4
apple         30.0    31.0    32.0    35.0
banana        34.0    35.0    36.0    37.0
kiwi          38.0    39.0    40.0    41.0
grape         42.0    43.0    44.0    45.0
mango         46.0    47.0    48.0    49.0
orange        50.0    51.0    52.0    53.0
pineapple     54.0    55.0    56.0    57.0
watermelon    30.0    31.0    32.0    33.0
strawberry     NaN     NaN     NaN     NaN

In [14]:
arr1=np.array([100,200,np.nan,300])
ser1=pd.Series(arr1)
arr1.mean(),ser1.mean()

(np.float64(nan), np.float64(200.0))

In [15]:
ser2=dfx.Store5
ser2.sum()

np.float64(34.0)

In [16]:
ser2.mean()

np.float64(34.0)

In [17]:
ser2.cumsum()

apple          NaN
banana         NaN
kiwi           NaN
grape          NaN
mango          NaN
orange         NaN
pineapple      NaN
watermelon    34.0
strawberry     NaN
Name: Store5, dtype: float64

In [18]:
filledDf=dfx.fillna(0)
filledDf

            Store1  Store2  Store3  Store4  Store5  Store6
apple         30.0    31.0    32.0    35.0     0.0     0.0
banana        34.0    35.0    36.0    37.0     0.0     0.0
kiwi          38.0    39.0    40.0    41.0     0.0     0.0
grape         42.0    43.0    44.0    45.0     0.0     0.0
mango         46.0    47.0    48.0    49.0     0.0     0.0
orange        50.0    51.0    52.0    53.0     0.0     0.0
pineapple     54.0    55.0    56.0    57.0     0.0     0.0
watermelon    30.0    31.0    32.0    33.0    34.0     0.0
strawberry     0.0     0.0     0.0     0.0     0.0     0.0

In [19]:
filledDf=dfx.fillna(48)
filledDf

            Store1  Store2  Store3  Store4  Store5  Store6
apple         30.0    31.0    32.0    35.0    48.0    48.0
banana        34.0    35.0    36.0    37.0    48.0    48.0
kiwi          38.0    39.0    40.0    41.0    48.0    48.0
grape         42.0    43.0    44.0    45.0    48.0    48.0
mango         46.0    47.0    48.0    49.0    48.0    48.0
orange        50.0    51.0    52.0    53.0    48.0    48.0
pineapple     54.0    55.0    56.0    57.0    48.0    48.0
watermelon    30.0    31.0    32.0    33.0    34.0    48.0
strawberry    48.0    48.0    48.0    48.0    48.0    48.0

In [20]:
dfx.mean()

Store1    40.50
Store2    41.50
Store3    42.50
Store4    43.75
Store5    34.00
Store6      NaN
dtype: float64

In [21]:
filledDf.mean()

Store1    41.333333
Store2    42.222222
Store3    43.111111
Store4    44.222222
Store5    46.444444
Store6    48.000000
dtype: float64

In [22]:
dfx.Store5.fillna(method='ffill')

/tmp/ipykernel_743/384304992.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.Store5.fillna(method='ffill')

apple          NaN
banana         NaN
kiwi           NaN
grape          NaN
mango          NaN
orange         NaN
pineapple      NaN
watermelon    34.0
strawberry    34.0
Name: Store5, dtype: float64

In [23]:
dfx.Store6.fillna(method='ffill')

/tmp/ipykernel_743/3139278759.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.Store6.fillna(method='ffill')

apple        NaN
banana       NaN
kiwi         NaN
grape        NaN
mango        NaN
orange       NaN
pineapple    NaN
watermelon   NaN
strawberry   NaN
Name: Store6, dtype: float64

In [24]:
dfx.Store5.fillna(method='bfill')

/tmp/ipykernel_743/160292402.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.Store5.fillna(method='bfill')

apple         34.0
banana        34.0
kiwi          34.0
grape         34.0
mango         34.0
orange        34.0
pineapple     34.0
watermelon    34.0
strawberry     NaN
Name: Store5, dtype: float64

In [25]:
dfx.Store6.fillna(method='bfill')

/tmp/ipykernel_743/1152094621.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.Store6.fillna(method='bfill')

apple        NaN
banana       NaN
kiwi         NaN
grape        NaN
mango        NaN
orange       NaN
pineapple    NaN
watermelon   NaN
strawberry   NaN
Name: Store6, dtype: float64

In [26]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [27]:
df=pd.DataFrame({"Age": [26,np.nan,43,13,34], "Salary": [35000,40000,np.nan,65000,80000], "Category":["A","B","A",np.nan,"B"]})
df

    Age   Salary Category
0  26.0  35000.0        A
1   NaN  40000.0        B
2  43.0      NaN        A
3  13.0  65000.0      NaN
4  34.0  80000.0        B

In [28]:
mean_imputer=SimpleImputer(strategy="mean")
df["Age_Mean"]=mean_imputer.fit_transform(df[["Age"]])
df

    Age   Salary Category  Age_Mean
0  26.0  35000.0        A      26.0
1   NaN  40000.0        B      29.0
2  43.0      NaN        A      43.0
3  13.0  65000.0      NaN      13.0
4  34.0  80000.0        B      34.0

In [29]:
median_imputer=SimpleImputer(strategy="median")
df["Salary_Median"]=median_imputer.fit_transform(df[["Salary"]])
df

    Age   Salary Category  Age_Mean  Salary_Median
0  26.0  35000.0        A      26.0        35000.0
1   NaN  40000.0        B      29.0        40000.0
2  43.0      NaN        A      43.0        52500.0
3  13.0  65000.0      NaN      13.0        65000.0
4  34.0  80000.0        B      34.0        80000.0

In [30]:
num_cols=["Age","Salary"]
mice_imputer=IterativeImputer(max_iter=10,random_state=42)
df_mice=df[num_cols].copy()
df_mice.iloc[:,:]=mice_imputer.fit_transform(df_mice)
df["Age_MICE"]=df_mice["Age"]
df["Salary_MICE"]=df_mice["Salary"]
print(df)

    Age   Salary Category  Age_Mean  Salary_Median   Age_MICE   Salary_MICE
0  26.0  35000.0        A      26.0        35000.0  26.000000  35000.000000
1   NaN  40000.0        B      29.0        40000.0  28.589615  40000.000000
2  43.0      NaN        A      43.0        52500.0  43.000000  55000.001291
3  13.0  65000.0      NaN      13.0        65000.0  13.000000  65000.000000
4  34.0  80000.0        B      34.0        80000.0  34.000000  80000.000000